apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mdm-auth-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
  - hosts:
      - {{ .Values.ingress.host.auth }}
    secretName: {{ .Values.ingress.tls_secret_name }}
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host.auth }}.{{ .Values.ingress.host_domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.names.auth }}
            port:
              number: {{ .Values.service.port.https }}
